homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-drivers
  - daviderestivo/emacs-head

homebrew_installed_packages:
  - deno
  # - emacs-head@28 --with-cocoa --with-native-comp --with-modern-icon-elrumo2
  # then run:
  # ln -s /usr/local/opt/emacs-head@28/Emacs.app /Applications
  - gcc # for emacs
  - git
  - fnm # better version of nvm
  - libgccjit # for emacs
  - texinfo  # for emacs
  # - nvm
  - zsh
  - zsh-autosuggestions
  - zsh-git-prompt
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - zsh-you-should-use

#  - dockutil

homebrew_cask_apps:
  - barrier
  #- cyberduck
  - dbeaver
  - dbngin
  - deepl
  #- docker
  #- emacs-mac-spacemacs-icon
  - fig
  - figma
  - firefox
  #- font-source-code-pro
  - gas-mask
  - github
  - google-chrome
  - hammerspoon
  - hpedrorodrigues/tools/dockutil
  - insomnia
  - iterm2
  - lastpass
  - marked
  #- multipass
  - notion
  - postman
  - ql-ansilove
  - qladdict
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlmobi
  - qlprettypatch
  - qlstephen
  - qlvideo
  - quicklook-csv
  - quicklook-json
  - quicklook-pfm
  - slack
  - spotify
  - synology-drive
  - telegram
  #- tidal
  #- timely
  - timeular
  - visual-studio-code
  - vmware-fusion
  - webpquicklook
  #- windscribe

#mas_installed_apps:
#  - { id: 443987910, name: "1Password" }
#  - { id: 498486288, name: "Quick Resizer" }
#  - { id: 557168941, name: "Tweetbot" }
#  - { id: 497799835, name: "Xcode" }

#composer_packages:
#  - name: hirak/prestissimo
#  - name: drush/drush
#    version: '^8.1'

#gem_packages:
#  - name: bundler
#    state: latest

#npm_packages:
#  - name: webpack

#pip_packages:
#  - name: mkdocs

configure_dotfiles: no
dotfiles_repo: https://github.com/einSelbst/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/
dotfiles_files:
  - .zshrc
  - .zshenv
  - .zshaliases
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

configure_dock: true
dockitems_remove:
  - Maps
  - TV
dockitems_persist:
  - name: "GitHub Desktop"
    path: "/Applications/GitHub Desktop.app/"
    pos: 5
